[mypy]
python_version = 3.10
strict = true
ignore_missing_imports = true
exclude = tests/

[mypy-mlx.*]
ignore_missing_imports = true

[mypy-mlx_lm.*]
ignore_missing_imports = true

[mypy-huggingface_hub.*]
ignore_missing_imports = true

[mypy-hf_transfer.*]
ignore_missing_imports = true

[mypy-psutil.*]
ignore_missing_imports = true
